**ASSIGNMENT 1:**
##### Submitted by: Manvi Mehendiyan
##### Roll No.: 102003678
##### Subgroup: 3COE27 

In [4]:
import numpy as np

QUESTION 1:

In [5]:
arr=np.array([1,2,3,6,4,5])
print(np.flip(arr))

[5 4 6 3 2 1]


In [6]:
array1=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(f"Initial array:\n{array1}")
a1D=array1.flatten()
print(f"New array: {a1D}")

Initial array:
[[1 2 3]
 [2 4 5]
 [1 2 3]]
New array: [1 2 3 2 4 5 1 2 3]


In [7]:
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[1, 2], [3, 4]])
compare= arr1==arr2
print(compare.all())

True


In [8]:
#(i)
x=np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
n=np.bincount(x).argmax()
print(f"Most frequent value: {n}")
print(np.where(x==n))

#(ii)
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
m=np.bincount(y).argmax()
print(f"Most frequent value: {m}")
print(np.where(y==m))

Most frequent value: 1
(array([0, 5, 7, 8, 9], dtype=int64),)
Most frequent value: 1
(array([0, 1, 2], dtype=int64),)


In [9]:
gfg=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"Given Matrix:\n{gfg}")
print("Sum of all elements:",gfg.sum())
print("Sum of all elements row-wise: \n",gfg.sum(axis=1))
print("Sum of all elements column-wise: ",gfg.sum(axis=0))

Given Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Sum of all elements row-wise: 
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:  [[20  9 16]]


In [10]:
n_array=np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(f"Given matrix:\n{n_array}")
print(f"Sum of diagonal elements: {n_array.trace()}")
w,v=np.linalg.eig(n_array)
print(f"Eigen values of matrix: {w}")
print(f"Eigen vectors of matrix:\n{v}")
print(f"Inverse of a matrix:\n{np.linalg.inv(n_array)}")
print(f"Determinant of matrix: {np.linalg.det(n_array)}")


Given matrix:
[[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diagonal elements: 176
Eigen values of matrix: [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of a matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [11]:
#(i)
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]] 
print(f"p*q=\n{np.matmul(p,q)}")
print(f"Covariance:\n{np.cov(p,q)}")

#(ii)
r = [[1, 2], [2, 3], [4, 5]]
s = [[4, 5, 1], [6, 7, 2]]
print(f"\np*q=\n{np.matmul(r,s)}")

p*q=
[[16 19]
 [26 31]]
Covariance:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

p*q=
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [12]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f"Inner product:\n{np.inner(x,y)}")
print(f"Outer product:\n{np.outer(x,y)}")
print(f"Cartesian product:\n{np.cross(x,y)}")

Inner product:
[[17 52]
 [13 62]]
Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[-20   4   7]
 [-84  36  20]]


QUESTION 2:

In [13]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(f"Element-wise absolute value:\n{np.absolute(array)}")

print("\nPercentile values of flattened array:")
print(f"25th: {np.percentile(array,25)}")
print(f"50th: {np.percentile(array,50)}")
print(f"75th: {np.percentile(array,75)}")
print("Percentile values of each column:")
print(f"25th: {np.percentile(array,25,axis=0)}")
print(f"50th: {np.percentile(array,50,axis=0)}")
print(f"75th: {np.percentile(array,75,axis=0)}")
print("Percentile values of each row:")
print(f"25th: {np.percentile(array,25,axis=1)}")
print(f"50th: {np.percentile(array,50,axis=1)}")
print(f"75th: {np.percentile(array,75,axis=1)}")

print(f'\nMean of flattened array is: {np.mean(array)}')
print(f'Median of flattened array is: {np.median(array)}')
print(f'Standard deviation of flattened array is: {np.std(array)}')

print(f'\nMean of array for each column is: {np.mean(array, axis=0)}')
print(f'Median of array for each column is: {np.median(array, axis=0)}')
print(f'Standard deviation of array for each column is: {np.std(array, axis=0)}')

print(f'\nMean of array for each row is: {np.mean(array, axis=1)}')
print(f'Median of array for each row is: {np.median(array, axis=1)}')
print(f'Standard deviation of array for each row is: {np.std(array, axis=1)}')

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

Percentile values of flattened array:
25th: -3.5
50th: -0.5
75th: 2.5
Percentile values of each column:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]
Percentile values of each row:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]

Mean of flattened array is: -0.5
Median of flattened array is: -0.5
Standard deviation of flattened array is: 3.8622100754188224

Mean of array for each column is: [-1.5  1.5 -1.5]
Median of array for each column is: [-1.5  1.5 -1.5]
Standard deviation of array for each column is: [2.5 3.5 4.5]

Mean of array for each row is: [ 0.66666667 -1.66666667]
Median of array for each row is: [ 1. -4.]
Standard deviation of array for each row is: [2.05480467 4.78423336]


In [14]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(f"Given array: {a}")
print(f"Floor values: {np.floor(a)}")
print(f"Ceiling values: {np.ceil(a)}")
print(f"Truncated values: {np.trunc(a)}")
print(f"Rounded values: {np.round(a)}")

Given array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


QUESTION 3:

In [15]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(f"Given array: {array}")
a=np.sort(array)
print(f"Sorted array: {a}")
print(f"Indices of sorted array: {np.argsort(array)}")
print(f"4 smallest elements: {a[:4]}")
print(f"5 largest elements: {a[:1:-1]}")

Given array: [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


In [16]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements in the array are: ")
for i in array:
    if(np.equal(np.mod(i, 1), 0)):
        print(i)
print("Float elements in the array are: ")
for i in array:
    if(not np.equal(np.mod(i, 1), 0)):
        print(i)

Integer elements in the array are: 
1.0
2.0
3.0
2.0
Float elements in the array are: 
1.2
2.2


QUESTION 4:

In [17]:
from PIL import Image  #PIL Python Imaging Library

def img_to_array(path):
    img = Image.open(path)
    global data
    data= np.asarray(img)
    print(f"Image shape: {data.shape}")
    # if image is colored (RGB)
    if(data.shape[2] == 3):
        data_reshape = data.reshape(data.shape[0], -1)
        print(f'Reshaping to 2D array: {data_reshape.shape}')
    # if image is greyscale
    else:
        data_reshape = data
    
    np.savetxt('output.txt', data_reshape, fmt="%d")
    print('Image Saved as Output.txt')

img_to_array('lazy.jpg')


Image shape: (799, 1200, 3)
Reshaping to 2D array: (799, 3600)
Image Saved as Output.txt


In [18]:
loaded_2D_mat = np.loadtxt('output.txt')
loaded_mat = loaded_2D_mat.reshape(
    loaded_2D_mat.shape[0], loaded_2D_mat.shape[1] // data.shape[2], data.shape[2])
print(f'Shape of loaded image: {loaded_mat.shape}')

if((data == loaded_mat).all()):
    print("The loaded image is same as original Image")

Shape of loaded image: (799, 1200, 3)
The loaded image is same as original Image
